name: Clean Colab Widget Metadata

on:
  push:
    paths:
      - '**/*.ipynb'
  workflow_dispatch:

jobs:
  clean-widgets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install nbformat

      - name: Remove widget metadata from notebooks
        run: |
          python << 'EOF'
          import os
          import nbformat

          def clean_widgets(path):
              with open(path, 'r', encoding='utf-8') as f:
                  nb = nbformat.read(f, as_version=4)
              if 'widgets' in nb.get('metadata', {}):
                  del nb['metadata']['widgets']
                  with open(path, 'w', encoding='utf-8') as f:
                      nbformat.write(nb, f)
                  return True
              return False

          changed = False
          for root, _, files in os.walk('.'):
              for file in files:
                  if file.endswith('.ipynb'):
                      path = os.path.join(root, file)
                      if clean_widgets(path):
                          print(f'Cleaned: {path}')
                          changed = True

          if not changed:
              print('No widgets metadata found.')
          EOF

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          # Update remote to use the provided GITHUB_TOKEN for authentication
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          # Recursively add notebooks
          find . -type f -name "*.ipynb" -exec git add {} +
          # Commit and push changes if there are any
          git diff --cached --quiet || (git commit -m "Remove widget metadata from notebooks" && git push origin HEAD:${{ github.ref }})
